spring.application.name=JPAEXAMINATION1


spring.datasource.url=jdbc:mysql://localhost:3306/JPAEXAMINATION
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD}
#spring.datasource.password=${MY_ENV_VARIABLE}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true